language: php

branches:
  only:
    - master
    - development

php:
  - 5.5
  - 5.4

env:
  - SILEX_VERSION=1.0.*
  - SILEX_VERSION=1.1.*
  - SILEX_VERSION=dev-master

before_script:
  - composer require silex/silex:${SILEX_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - mudi@renegare.com